#!/bin/bash

RESET_ALL=$(tput sgr0)
BOLD=$(tput bold)
YELLOW="${BOLD}$(tput setaf 3)"

README_FILENAME="README.md"

warning() {
	local mesg=$1
	shift
	printf "${YELLOW}[WARNING]${RESET_ALL} ${BOLD}${mesg}${RESET_ALL}\n" "$@" >&2
}

function check_readme() {
	local dir="${1:-.}"
	local readme_path="$dir/$README_FILENAME"

	if [[ ! -f "${readme_path}" ]]; then
		warning "readme missing ${readme_path}"
		return 1
	fi
	return 0
}

root_dir="$(git rev-parse --show-toplevel)"
check_readme "${root_dir}"
