#!/bin/bash

RESET_ALL=$(tput sgr0)
BOLD=$(tput bold)
YELLOW="${BOLD}$(tput setaf 3)"

CHANGELOG_FILENAME="CHANGELOG.md"

warning() {
	local mesg=$1
	shift
	printf "${YELLOW}[WARNING]${RESET_ALL} ${BOLD}${mesg}${RESET_ALL}\n" "$@" >&2
}

function check_changelog() {
	local dir="${1:-.}"
	local changelog_path="$dir/$CHANGELOG_FILENAME"

	if [[ ! -f "${changelog_path}" ]]; then
		warning "change log missing ${changelog_path}"
		return 1
	fi
	return 0
}

function changelog_committed() {
	local dir="${1:-.}"
	git diff-tree --no-commit-id --name-only -r HEAD \
		--exit-code -- "${dir}/${CHANGELOG_FILENAME}" &> /dev/null
	if [[ $? -eq 0 ]]; then
		return 1
	else
		return 0
	fi
}

function check_changelog_not_updated() {
	local dir="${1:-.}"
	changelog_committed "${dir}"
	if [[ $? -eq 1 ]]; then
		warning "change log has not been updated ${dir}/${CHANGELOG_FILENAME}"
	fi
}

root_dir="$(git rev-parse --show-toplevel)"
check_changelog "${root_dir}"
check_changelog_not_updated "${root_dir}"
