#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

if [[ $# -ne 1 ]]; then
	echo "Usage: copy-commit <git-repo>"
fi
path="$1"

# Checks if the given path is a Git repository
git -C "$path" rev-parse --is-inside-work-tree > /dev/null
if [[ $? -ne 0 ]]; then
	echo "Not a Git repository"
	exit 1
fi

# Gets the root directory of the repository
root_dir="$(git -C "$path" rev-parse --show-toplevel)"
hooks_dir="$root_dir/.git/hooks"

# Copy post commit scripts
printf "Copying post-commit scripts\n"
install -m755 "$SCRIPT_DIR/post-commit" "$hooks_dir"
install -d "$hooks_dir/post-commit.d"
install -m755 "$SCRIPT_DIR/post-commit.d/"* "$hooks_dir/post-commit.d"
